# This file is part of the TUM Overleaf template.
# It is used to point the LaTeX Compiler to the class and package files
# located in the tum/ subdirectory.

use Config;
$ENV{'TEXINPUTS'} = './tum//' . $Config::Config{path_sep} . ($ENV{'TEXINPUTS'} // '');
